import 'dart:ui';

/// Locale-aware strings for the LCM report generator (no BuildContext).
/// Report is user-facing (markdown / shared PDF), so it follows the UI language.
class RapportStrings {
  final bool nl;
  RapportStrings() : nl = PlatformDispatcher.instance.locale.languageCode.toLowerCase() == 'nl';
  RapportStrings.withLocale(String code) : nl = code.toLowerCase().startsWith('nl');

  String get lifeChartTitle =>
      nl ? '# Life Chart Methode — Ritme Rapport' : '# Life Chart Method — Ritme Report';
  String get disclaimer => nl
      ? '**Dit rapport is bedoeld als ondersteunend overzicht bij de behandeling van een Bipolaire Stoornis.**'
      : '**This report is intended as a supporting overview in the treatment of Bipolar Disorder.**';
  String get period => nl ? '**Periode:**' : '**Period:**';
  String get generated => nl ? '**Gegenereerd:**' : '**Generated:**';
  String get to => nl ? 't/m' : 'to';

  String get moodCheckTitle => nl
      ? '🧠 Stemmingscheck (5 vragen)'
      : '🧠 Mood check (5 questions)';
  String get intakeMoments => nl ? 'invulmomenten' : 'entries';

  String get metric => nl ? 'Metriek' : 'Metric';
  String get average => nl ? 'Gemiddelde' : 'Average';
  String get mood => nl ? 'Stemming' : 'Mood';
  String get energy => nl ? 'Energie' : 'Energy';
  String get energyLevel => nl ? 'Energie-niveau' : 'Energy level';
  String get sleepNeed => nl ? 'Slaapbehoefte' : 'Sleep need';
  String get importantEvent => nl ? 'Belangrijke gebeurtenis' : 'Important event';
  String get calculatedMood => nl ? 'Berekende stemming' : 'Calculated mood';

  String get weeklyOverview => nl ? '📊 Weekoverzicht' : '📊 Weekly overview';
  String get week => nl ? 'Week' : 'Week';
  String get avgMood => nl ? 'Gem. stemming' : 'Avg. mood';
  String get avgSleep => nl ? 'Gem. slaap' : 'Avg. sleep';
  String get avgPScore => nl ? 'Gem. P-Score' : 'Avg. P-Score';
  String get medication => nl ? 'Medicatie' : 'Medication';

  String get daysWithData => nl ? 'Dagen met data' : 'Days with data';
  String get avgMoodLong => nl ? 'Gem. stemming' : 'Avg. mood';
  String get avgSleepDuration => nl ? 'Gem. slaapduur' : 'Avg. sleep duration';
  String get medicationAdherence => nl ? 'Medicatie-trouw' : 'Medication adherence';
  String get taken => nl ? 'ingenomen' : 'taken';
  String get unknown => nl ? 'Onbekend' : 'Unknown';
  String get lastBloodLevel => nl ? 'Laatste bloedspiegel' : 'Last blood level';

  String get warnings => nl ? '⚠️ Voortekenen' : '⚠️ Early warning signs';
  String totalWarnings(int n) =>
      nl ? 'Totaal voortekenen in periode: **$n**' : 'Total early warning signs in period: **$n**';
  String warningsCount(int n) => nl ? '$n voortekenen' : '$n warning signs';

  String get crisisPlan => nl ? '🚨 Crisisplan' : '🚨 Crisis plan';
  String get medTakenDays => nl ? '💊 Medicatie — ingenomen dagen' : '💊 Medication — days taken';
  String get med => nl ? '💊 Medicatie' : '💊 Medication';
  String get episodesTitle => nl ? '🏥 Episodes' : '🏥 Episodes';

  String get footer => nl
      ? '*Rapport gegenereerd door Ritme — SRT Tracker*'
      : '*Report generated by Ritme — SRT Tracker*';

  String formatHours(double uren) {
    final min = (uren * 60).round();
    final h = min ~/ 60;
    final m = min % 60;
    final u = nl ? 'u' : 'h';
    if (m == 0) return '$h$u';
    return '$h$u ${m}m';
  }

  String episodeLabel(String type) {
    switch (type) {
      case 'hypomanie': return nl ? 'Hypomanie' : 'Hypomania';
      case 'manie': return nl ? 'Manie' : 'Mania';
      case 'depressie': return nl ? 'Depressie' : 'Depression';
      case 'gemengd': return nl ? 'Gemengd' : 'Mixed';
      case 'euthym': return nl ? 'Stabiel' : 'Stable';
      default: return type;
    }
  }

  String? flagLabel(String id) {
    if (nl) {
      switch (id) {
        case 'maniaShift': return 'Mogelijke manische shift';
        case 'probableMania': return 'Waarschijnlijke manie (triade)';
        case 'sleepReductionAlone': return 'Verminderde slaapbehoefte (vroeg manie-signaal)';
        case 'depressionShift': return 'Mogelijke depressieve shift';
        case 'probableDepression': return 'Waarschijnlijke depressie (triade)';
        case 'positiveLifeEventTrigger': return 'Positieve gebeurtenis als manie-trigger';
        case 'negativeLifeEventTrigger': return 'Negatieve gebeurtenis als depressie-trigger';
        case 'mixedEpisode': return 'Mogelijke gemengde episode';
        case 'opposingSignals': return 'Tegenstrijdige signalen';
        default: return null;
      }
    }
    switch (id) {
      case 'maniaShift': return 'Possible manic shift';
      case 'probableMania': return 'Probable mania (triad)';
      case 'sleepReductionAlone': return 'Reduced need for sleep (early mania sign)';
      case 'depressionShift': return 'Possible depressive shift';
      case 'probableDepression': return 'Probable depression (triad)';
      case 'positiveLifeEventTrigger': return 'Positive event as mania trigger';
      case 'negativeLifeEventTrigger': return 'Negative event as depression trigger';
      case 'mixedEpisode': return 'Possible mixed episode';
      case 'opposingSignals': return 'Opposing signals';
      default: return null;
    }
  }

  String sectionTitle(String section) {
    if (nl) {
      switch (section) {
        case 'manie_vroeg': return 'Bij eerste tekenen van manie';
        case 'manie_ernstig': return 'Bij ernstige manie';
        case 'depressie_vroeg': return 'Bij eerste tekenen van depressie';
        case 'depressie_ernstig': return 'Bij ernstige depressie';
        case 'gemengd': return 'Bij gemengde episode';
        case 'contacten': return 'Belangrijke contacten';
        case 'medicatie_nood': return 'Medicatie noodplan';
        case 'wat_helpt': return 'Wat helpt mij';
        default: return section;
      }
    }
    switch (section) {
      case 'manie_vroeg': return 'At first signs of mania';
      case 'manie_ernstig': return 'In severe mania';
      case 'depressie_vroeg': return 'At first signs of depression';
      case 'depressie_ernstig': return 'In severe depression';
      case 'gemengd': return 'In a mixed episode';
      case 'contacten': return 'Important contacts';
      case 'medicatie_nood': return 'Medication emergency plan';
      case 'wat_helpt': return 'What helps me';
      default: return section;
    }
  }
}
